server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Vidarebefordra /api/ till proxy-containern
    location /api/ {
        proxy_pass http://sl-proxy:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
